bug fix in error messaging

diff --git a/ub_def b/ub_def
--- a/ub_def
+++ b/ub_def
@@ -7,9 +7,12 @@ fi
 
 curl -s http://api.urbandictionary.com/v0/define?term="$1" |  python3 -c 'import json,sys;obj=json.load(sys.stdin);print (obj["list"]['$INDEX']["definition"])' 2> /dev/null
 
-if [ $? -gt 0 ] && [ -n "$2" ] && [ $2 -gt 0 ]; then
+ERRORR="$?"
+
+if [ "$ERRORR" -gt 0 ] && [ -n "$2" ] && [ "$2" -gt 0 ]; then
     echo "out of range";
-elif [ $? -gt 0 ]; then
+elif [ "$ERRORR" -gt 0 ]; then
+    echo "error = $ERRORR"
     echo "no definition";
 fi
 
