urban dictionary script improved

diff --git a/ub_def b/ub_def
--- a/ub_def
+++ b/ub_def
@@ -1,14 +1,15 @@
 #!/bin/bash
 echo "$@"
-echo "$2"
-echo "end"
+#echo "$2"
+#echo "end"
 
 INDEX=0
-
 if [ -n "$2" ];then
     INDEX="$2"
 fi
+
 TERM=${1// /%20}
+
 if [ $# -gt 2 ];then
     echo "$TERM"
 fi
@@ -18,10 +19,13 @@ ERRORR="$?"
 
 if [ "$ERRORR" -gt 0 ] && [ -n "$2" ] && [ "$2" -gt 0 ]; then
     echo "out of range";
+    echo "error = $ERRORR"
 elif [ "$ERRORR" -gt 0 ]; then
     echo "error = $ERRORR"
     echo "no definition";
 fi
+
+exit $ERRORR
 
 isNumberX() {
     re='^[0-9]+$'
